### ISSUE TITLE
Validate promises are actually promises

### ISSUE THREAD

**Issue by Etromania** [jwlawrence/ember-tri-state#6]
We make an assumption promises are provided to the promises argument. If a non-promise is provided it silently "dies" when it enters the PromiseObject. It would be useful to clear data if `null` is provided to clear out values. With the current logic, the component ignores non-promise values and keeps displaying the last saved values present since the `triState` computed property is never reached.

We should talk about how to handle these cases but it seems like something we should probably handle internally by expanding the `_resolvePromises` method with a sanitization step which would convert non-promise data to a resolved promise.

**Comment by jwlawrence** [comment]
As suggested, if the type of `promises` is anything other than a thenable, object, or array, we now wrap the value in a `Promise.resolve()`. See https://github.com/jwlawrence/ember-tri-state/commit/873d74776743e31ec7321da7c8575d6347f7233b
